### ISSUE TITLE
yajl2_cffi backend type error

### ISSUE THREAD

**Issue by vrastogi** [isagalaev/ijson#54]
With the following minimal example

```
import sys
import ijson.backends.yajl2_cffi as ijson
# import ijson

items = ijson.items(open(sys.argv[1]), 'item')
for item in items:
    print(item)
```

and a simple json file containing, for example, `[1,2,3]`

I get the following error

> 
> Traceback (most recent call last):
>   File "minimal_example.py", line 6, in <module>
>     for item in items:
>   File "/usr/local/lib/python3.5/dist-packages/ijson/common.py", line 138, in items
>     current, event, value = next(prefixed_events)
>   File "/usr/local/lib/python3.5/dist-packages/ijson/common.py", line 65, in parse
>     for event, value in basic_events:
>   File "/usr/local/lib/python3.5/dist-packages/ijson/backends/yajl2_cffi.py", line 218, in basic_parse
>     yajl_parse(handle, buffer)
>   File "/usr/local/lib/python3.5/dist-packages/ijson/backends/yajl2_cffi.py", line 179, in yajl_parse
>     result = yajl.yajl_parse(handle, buffer, len(buffer))
> TypeError: initializer for ctype 'unsigned char *' must be a bytes or list or tuple, not str

There is no error when using the pure python backend.

Using Python 3.5, Ubuntu 16.04 with OS-packaged yajl2. ijson==2.3; cffi==1.7.0

Will be happy to provide other information.

**Comment by isagalaev** [comment]
In Python 3 `open()` gives you a stream producing Python's unicode strings, and the underlying yajl doesn't know how to deal with those. So, the correct way of parsing JSON files is actually to open them in `'rb'` mode.

The fact that it seems to work in other libraries is due to legacy expectations of strings and bytes being interchangeable, so they (and us, in the Python backend) explicitly support unicode input in one way or another. yajl is simply more strict in this regard. And I'd say they're right because JSON is actually *defined* as a utf-8 encoded stream of bytes.

**Comment by vrastogi** [comment]
Thanks for the quick response and pointing out the problem in my code. Closing the issue.
